name: Docker Build and Push to ACR

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        default: dev
        type: string
      dockerfile_path:
        required: false
        default: ./Dockerfile
        type: string
      context:
        required: false
        default: .
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      ACR_NAME:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.image_tag }}
