name: Propagate build_call.yml to other repos

on:
  push:
    paths:
      - 'call_templates/build_call.yml'

jobs:
  propagate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y jq

    - name: Run propagation script
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        #!/bin/bash
        set -ex  # Enable debugging

        REPOS=("service-discovery" "cloud-config" "api-gateway" "proxy-client" "order-service" "payment-service" "product-service" "shipping-service" "user-service" "favourite-service")
        BRANCHES=("main" "develop" "stage")
        ORG="microservices-final-project"

        # Configure git globally
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        for repo in "${REPOS[@]}"; do
          echo "🔄 Processing repo: $repo"
          git clone --quiet "https://x-access-token:${GH_PAT}@github.com/${ORG}/${repo}.git"
          cd "$repo"
          
          # Set the remote URL with PAT
          git remote set-url origin "https://x-access-token:${GH_PAT}@github.com/${ORG}/${repo}.git"

          for branch in "${BRANCHES[@]}"; do
            if git ls-remote --exit-code --heads origin "$branch" >/dev/null; then
              echo "⏳ Processing branch: $branch"
              git checkout "$branch"
              git pull origin "$branch"

              mkdir -p .github/workflows
              cp ../call_templates/build_call.yml .github/workflows/build.yml

              git add .github/workflows/build.yml
              
              if ! git diff-index --quiet HEAD --; then
                git commit -m "chore: sync build.yml from central repo"
                git push origin "$branch"
                echo "✅ Successfully updated $repo/$branch"
              else
                echo "🔸 No changes in $repo/$branch"
              fi
            else
              echo "⚠️ Branch $branch doesn't exist in $repo. Skipping."
            fi
          done

          cd ..
          rm -rf "$repo"
        done