name: Promote Secret to Organization

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to promote'
        required: true
      secret_value:
        description: 'Value of the secret (optional if already in repo)'
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Fetch secret value (if not provided)
        id: get-secret
        run: |
          if [ -z "${{ github.event.inputs.secret_value }}" ]; then
            secret_value=$(gh secret list --repo "${{ github.repository }}" --json name | jq -r '.[] | select(.name=="${{ github.event.inputs.secret_name }}")')
            if [ -z "$secret_value" ]; then
              echo "Secret ${{ github.event.inputs.secret_name }} not found in the repo"
              exit 1
            fi
            echo "value=$(gh secret view ${{ github.event.inputs.secret_name }} --repo ${{ github.repository }} --json value -q .value)" >> $GITHUB_OUTPUT
          else
            echo "value=${{ github.event.inputs.secret_value }}" >> $GITHUB_OUTPUT
          fi

      - name: Promote secret to org
        run: |
          gh secret set ${{ github.event.inputs.secret_name }} \
            --org microservices-final-project \
            --body "${{ steps.get-secret.outputs.value }}"
