name: Run Postman Tests with Newman

on:
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman collection with environment variable
        run: |
          newman run api_gateway.postman_collection.json

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://52.249.246.58:8080'  # o la URL donde corre tu API Gateway
          fail_action: false
