name: SonarQube Analysis

on:
  workflow_call:
    inputs:
      projectKeyBase:
        required: true
        type: string
      projectNameBase:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Sanitize branch name
        id: sanitize
        run: |
          RAW_NAME="${{ github.head_ref }}"
          SAFE_NAME=$(echo "$RAW_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "safe_branch_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download sonar-project.properties from ci-templates
        run: |
          git clone --depth=1 https://github.com/microservices-final-project/ci-templates temp-templates
          cp temp-templates/sonar-project.properties .
          sed -i "s/default-key/${{ inputs.projectKeyBase }}-${{ steps.sanitize.outputs.safe_branch_name }}/" sonar-project.properties
          sed -i "s/default-name/${{ inputs.projectNameBase }} (${{ steps.sanitize.outputs.safe_branch_name }})/" sonar-project.properties

      - name: Build with tests and generate coverage
        run: mvn clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
