name: SonarQube Analysis

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
      projectName:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download sonar-project.properties from ci-templates
        run: |
          git clone --depth=1 https://github.com/microservices-final-project/ci-templates temp-templates
          cp temp-templates/sonar-project.properties .
          sed -i "s/default-key/${{ inputs.projectKey }}/" sonar-project.properties
          sed -i "s/default-name/${{ inputs.projectName }}/" sonar-project.properties

      - name: Compile project (generate target/classes)
        run: mvn clean compile

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
